[env]
PORT = "8000"

[config]
skip_core_tasks = true

# ---- SITE ----

[tasks.site]
description = "Build the site and move files to docs folder"
dependencies = ["site_clean","site_release", "site_statics"]

[tasks.site_serve]
description = "Start server from docs folder"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["--port", "${PORT}", "docs"]
dependencies = ["site"]

[tasks.site_clean]
command = "rm"
args = ["-rf", "docs"]

[tasks.site_release]
description = "Build with wasm-pack in release mode to docs/pkgs folder"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--release", "--out-dir", "docs/pkg"]

[tasks.site_statics]
dependencies = ["site_statics_assets", "site_statics_index", "site_statics_sw", "site_statics_styles", "site_statics_manifest"]

[tasks.site_statics_assets]
command = "cp"
args = ["-r", "assets", "docs/."]

[tasks.site_statics_index]
command = "cp"
args = ["index.html", "docs/."]

[tasks.site_statics_sw]
command = "cp"
args = ["service-worker.js", "docs/."]

[tasks.site_statics_styles]
command = "cp"
args = ["-r", "styles", "docs/."]

[tasks.site_statics_manifest]
command = "cp"
args = ["tasknet.webmanifest", "docs/."]

# ---- BASIC ----

[tasks.watch]
description = "Watch files and recompile the project on change"
dependencies = ["verify", "build"]
watch = true

[tasks.serve]
description = "Start server"
install_crate = { crate_name = "microserver", binary = "microserver", test_arg = "-h" }
command = "microserver"
args = ["--port", "${PORT}"]

[tasks.verify]
description = "Format, lint with Clippy and run tests"
dependencies = ["fmt", "clippy", "test", "test_browser_headless_firefox"]

[tasks.clean]
dependencies = ["clean_target", "clean_pkg"]

[tasks.clean_target]
command = "cargo"
args = ["clean"]

[tasks.clean_pkg]
command = "cargo"
args = ["clean", "--target-dir", "pkg"]

# ---- BUILD ----

[tasks.build]
description = "Build with wasm-pack"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_release]
description = "Build with wasm-pack in release mode"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "--target", "web", "--out-name", "package"]

# ---- LINT ----

[tasks.clippy]
description = "Lint with Clippy"
install_crate = { rustup_component_name = "clippy", binary = "cargo-clippy", test_arg = "--help" }
command = "cargo"
args = ["clippy", "--all-features", "--", "--deny", "warnings", "--deny", "clippy::pedantic", "--deny", "clippy::nursery"]

[tasks.fmt]
description = "Format with rustfmt"
install_crate = { rustup_component_name = "rustfmt", binary = "rustfmt", test_arg = "-V" }
command = "cargo"
args = ["fmt"]


# ---- TEST ----

[tasks.test_browser_headless]
description = "Run headless tests for browsers. Ex: 'cargo make test_browser_headless firefox'. Test envs: [chrome, firefox, safari]"
extend = "test_browser"
args = ["test", "--headless", "--${@}"]

[tasks.test_browser_headless_firefox]
description = "Run headless tests with Firefox."
extend = "test_browser"
args = ["test", "--headless", "--firefox"]

[tasks.test_browser]
description = "Run tests for browsers. Ex: 'cargo make test_browser firefox'. Test envs: [chrome, firefox, safari]"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["test", "--${@}"]

[tasks.test]
description = "Run tests"
command = "cargo"
args = ["test"]
