apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tasknet
  name: tasknet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasknet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tasknet
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Chart.Name }}
        env:
        - name: RUST_LOG
          value: info
