[package]
name = "tasknet-server"
version = "0.1.0"
authors = ["Andrew Jeffery <dev@jeffas.io>"]
edition = "2018"

[dependencies]
env_logger = "0.8.3"
futures-util = "0.3.12"
tokio = { version = "1.2.0", features = ["macros", "rt-multi-thread"] }
warp = "0.3.0"
