name: CD

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions-rs/cargo@v1
        with:
          command: test

  deploy:
    name: Deploy
    needs:
      - check
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - name: Install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.17.1/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Build package
      run: cd web && ../trunk build --release --public-url "/tasknet"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: web/dist
