name: CD

on:
  push:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Run checks
      run: nix flake check -L

  deploy:
    name: Deploy
    needs:
      - checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - name: Build web
      run: nix build -L .#tasknet-web-github
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: result
